### ISSUE TITLE
Add Papers section

### ISSUE THREAD

**Issue by rmrao** [CannyLab/cannylab.github.io#2]
Add a papers section w/ automatic search over John's google scholar profile:

[This](https://github.com/scholarly-python-package/scholarly/tree/master/scholarly) may be useful as an example.

**Comment by DavidMChan** [comment]
The right query for this would be something like:
```
https://scholar.google.com/citations?hl=en&user=LAv0HTEAAAAJ&view_op=list_works&sortby=pubdate&pagesize=80
```

However you have to write some code to parse out the actual table. 

Somebody has done this in PHP: https://github.com/dschreij/scholar_parser

**Comment by rmrao** [comment]
This might also help: https://github.com/toolbuddy/ScholarJS

**Comment by DavidMChan** [comment]
One thing that might be worth mentioning is that auto-filling the papers section won't give us the ability to add links to code, or other useful things like pull the abstract to the website. If this is functionality that we want, perhaps it's best to add papers manually (or perhaps create some kind of form that people can use to add a paper).

**Comment by DavidMChan** [comment]
So, I think the closest we can get to clean data is this:
```
https://scholar.google.com/citations?user=LAv0HTEAAAAJ&view_op=list_works&pagesize=100&json
```
It'll require a bit of parsing - but I don't think there's anything else we can do.
