### ISSUE TITLE
Add People page

### ISSUE THREAD

**Issue by rmrao** [CannyLab/cannylab.github.io#4]
Add a page with people in the lab (current grad students + undergrads)

Optionally also add former grad students + where they have gone.

Should contain images of people + links to personal websites.

**Comment by DavidMChan** [comment]
For both this issue, and #3  - how do we want the navigation to work? Should I add an additional navbar on the top? Or should I just add links to the existing single-page navigation?

**Comment by rmrao** [comment]
IMO if we're jumping between different pages it's better to have a navbar at the top, so that it's constant across different pages.

**Comment by DanielTakeshi** [comment]
From Professor Canny's website. Some of these are outdated. For example, Jingtao Wang is now at Google and Huasha Zhao is at Alibaba (edit: Microsoft again :) ). It is also missing Jinkyu Kim among the lab's graduates.

Former Ph.D. Students
Paul Jacobs, 1989 (Qualcomm)
Greg Heinzinger, 1990 (Qualcomm)
Dinesh Manocha, 1992 (UNC)
Ming Lin, 1994 (UNC)
Ioannis Emiris, 1994 (University of Athens)
Aaron Wallack, 1995 (Cognex)
Ashu Rege, 1996 (NVidia)
Brian Mirtich, 1996 (Mathworks)
Yan Zhuang, 2000 (Qualcomm, number 3!)
Dan Reznik, 2000 (e-Solar)
Eric Paulos, 2001 (CMU)
Francesca Barrientos, 2002 (NASA)
Dan Glaser, 2004, (RPI)
Tom Duan, 2007, (Yodao, China)
David Nguyen, 2008, (Accenture)
Jeremy Risner, 2008, (e-Solar)
Ana Ramirez-Chang, 2008 (Oracle)
Matthew Kam, 2008 (CMU)
Tye Rattenbury, 2008 (Intel)
Jingtao Wang, 2010 (U. Pittsburgh)
Divya Ramachandran, 2010
Reza Naima, 2012
Andy Carle, 2012 (Marvell)
Anuj Tewari, 2013 (GE Software)
Huasha Zhao, 2014
Pablo Paredes, 2015 (Stanford Radiology)
Biye Jiang, 2018

last updated 7/18/19

**Comment by DavidMChan** [comment]
I've updated the page to look something like this in #7 :

![image](https://user-images.githubusercontent.com/3190178/84948093-09916180-b0a0-11ea-8dbd-706ac65b5775.png)

What do you think?
