### ISSUE TITLE
TAPE image has weird aspect ratio

### ISSUE THREAD

**Issue by DavidMChan** [CannyLab/cannylab.github.io#5]
The image for TAPE has an odd aspect ratio (which is intrinsic to the file, it's not an issue with the webpage). It would be great if we could fix this.

**Comment by rmrao** [comment]
haha yes, I need to get a better image. I did this one quickly by stretching an image I already had to fit, but I'll fix it.

**Comment by DavidMChan** [comment]
Fixed in #6
